import collections.abc
import typing
from typing import overload

class Molecule:
    def __init__(self, *args, **kwargs) -> None: ...
    @staticmethod
    def from_rdkit_mol(arg0: object) -> Molecule: ...
    @staticmethod
    def from_smiles(arg0: str) -> Molecule: ...
    def largest_fragment(self) -> Molecule: ...
    def num_heavy_atoms(self) -> int: ...
    def smiles(self) -> str: ...
    def to_rdkit_mol(self) -> object: ...

class MoleculeError(RuntimeError): ...

class PrecursorMolecule:
    def __init__(self, *args, **kwargs) -> None: ...
    @property
    def item_index(self) -> int: ...
    @property
    def molecule(self) -> Molecule: ...
    @property
    def precursor_index(self) -> int: ...
    @property
    def precursor_node(self): ...
    @property
    def reactant_name(self) -> str: ...

class Reaction:
    def __init__(self, *args, **kwargs) -> None: ...
    @overload
    def apply(self, reactants: collections.abc.Mapping[str, Molecule], ignore_errors: bool = ...) -> list[ReactionOutcome]: ...
    @overload
    def apply(self, reactants: collections.abc.Sequence[Molecule], ignore_errors: bool = ...) -> list[ReactionOutcomeWithReactantAssignment]: ...
    @overload
    @staticmethod
    def from_smarts(smarts: str, reactant_names: collections.abc.Sequence[str]) -> Reaction: ...
    @overload
    @staticmethod
    def from_smarts(arg0: str) -> Reaction: ...
    def match_reactants(self, arg0: Molecule) -> list: ...
    def num_reactants(self) -> int: ...
    def reactant_names(self) -> list[str]: ...

class ReactionError(RuntimeError): ...

class ReactionOutcome:
    def __init__(self, *args, **kwargs) -> None: ...
    def empty(self) -> bool: ...
    def main_product(self) -> Molecule: ...
    def num_products(self) -> int: ...
    @property
    def products(self) -> list[Molecule]: ...

class ReactionOutcomeWithReactantAssignment(ReactionOutcome):
    def __init__(self, *args, **kwargs) -> None: ...
    @property
    def reactant_names(self) -> list[str]: ...

class Synthesis:
    def __init__(self) -> None: ...
    def nodes(self) -> list[SynthesisNode]: ...
    def push_molecule(self, molecule: Molecule) -> None: ...
    def push_reaction(self, reaction: Reaction, max_outcomes: typing.SupportsInt | typing.SupportsIndex | None) -> None: ...
    def stack_size(self) -> int: ...
    def stack_top(self, i: typing.SupportsInt | typing.SupportsIndex = ...) -> SynthesisNode: ...
    def undo(self) -> None: ...

class SynthesisError(RuntimeError): ...

class SynthesisNode:
    def __init__(self, *args, **kwargs) -> None: ...
    def at(self, i: typing.SupportsInt | typing.SupportsIndex) -> Molecule: ...
    def index(self) -> int: ...
    def precursor_nodes(self) -> list[SynthesisNode]: ...
    def precursors(self, index: typing.SupportsInt | typing.SupportsIndex) -> list[PrecursorMolecule]: ...
    def size(self) -> int: ...
