import collections.abc
import enum
import os
import prexsyn_engine.chemistry
import typing
from typing import Callable, ClassVar, overload

BuildingBlock: PostfixNotationTokenType
Reaction: PostfixNotationTokenType

class BuildingBlockCSVConfig:
    identifier_column: str
    smiles_column: str
    def __init__(self) -> None: ...

class BuildingBlockEntry:
    identifier: str
    labels: set[str]
    molecule: prexsyn_engine.chemistry.Molecule
    def __init__(self) -> None: ...

class BuildingBlockItem(BuildingBlockEntry):
    def __init__(self) -> None: ...
    @property
    def index(self) -> int: ...

class BuildingBlockLibrary:
    def __init__(self) -> None: ...
    def add(self, entry: BuildingBlockEntry) -> int: ...
    @staticmethod
    def deserialize(path: os.PathLike | str | bytes) -> BuildingBlockLibrary: ...
    @overload
    def get(self, index: typing.SupportsInt | typing.SupportsIndex) -> BuildingBlockItem: ...
    @overload
    def get(self, identifier: str) -> BuildingBlockItem: ...
    def serialize(self, path: os.PathLike | str | bytes) -> None: ...
    def size(self) -> int: ...
    def __getitem__(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> BuildingBlockItem: ...
    def __len__(self) -> int: ...

class BuildingBlockLibraryError(RuntimeError): ...

class BuildingBlockPreprocessor:
    largest_fragment_only: bool
    def __init__(self) -> None: ...

class ChemicalSpace:
    def __init__(self, bb_lib: BuildingBlockLibrary, rxn_lib: ReactionLibrary, int_lib: IntermediateLibrary, matching_config: ReactantMatchingConfig = ...) -> None: ...
    def bb_lib(self) -> BuildingBlockLibrary: ...
    def build_reactant_lists_for_building_blocks(self) -> None: ...
    def build_reactant_lists_for_intermediates(self) -> None: ...
    def building_block_reactant_lists(self) -> ReactantLists: ...
    @staticmethod
    def deserialize(path: os.PathLike | str | bytes) -> ChemicalSpace: ...
    def generate_intermediates(self) -> None: ...
    def int_lib(self) -> IntermediateLibrary: ...
    def intermediate_reactant_lists(self) -> ReactantLists: ...
    def new_synthesis(self, *args, **kwargs): ...
    @overload
    @staticmethod
    def peek(arg0: bytes) -> ChemicalSpacePeekStats: ...
    @overload
    @staticmethod
    def peek(arg0: os.PathLike | str | bytes) -> ChemicalSpacePeekStats: ...
    def print_reactant_lists(self) -> str: ...
    def reactant_matching_config(self) -> ReactantMatchingConfig: ...
    def rxn_lib(self) -> ReactionLibrary: ...
    def serialize(self, path: os.PathLike | str | bytes) -> None: ...

class ChemicalSpacePeekStats:
    def __init__(self) -> None: ...
    @property
    def num_building_blocks(self) -> int: ...
    @property
    def num_intermediates(self) -> int: ...
    @property
    def num_reactions(self) -> int: ...

class IntermediateEntry:
    identifier: str
    molecule: prexsyn_engine.chemistry.Molecule
    postfix_notation: PostfixNotation
    def __init__(self) -> None: ...

class IntermediateItem(IntermediateEntry):
    def __init__(self) -> None: ...
    @property
    def index(self) -> int: ...

class IntermediateLibrary:
    def __init__(self) -> None: ...
    def add(self, entry: IntermediateEntry) -> int: ...
    def clear(self) -> None: ...
    @staticmethod
    def deserialize(path: os.PathLike | str | bytes) -> IntermediateLibrary: ...
    @overload
    def get(self, index: typing.SupportsInt | typing.SupportsIndex) -> IntermediateItem: ...
    @overload
    def get(self, identifier: str) -> IntermediateItem: ...
    def serialize(self, path: os.PathLike | str | bytes) -> None: ...
    def size(self) -> int: ...
    def __getitem__(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> IntermediateItem: ...
    def __len__(self) -> int: ...

class PostfixNotation:
    def __init__(self) -> None: ...
    def append(self, index: typing.SupportsInt | typing.SupportsIndex, type: PostfixNotationTokenType) -> None: ...
    def extend(self, tokens: collections.abc.Sequence[PostfixNotationToken]) -> None: ...
    def pop_back(self) -> None: ...
    def tokens(self) -> list[PostfixNotationToken]: ...

class PostfixNotationToken:
    index: int
    type: PostfixNotationTokenType
    def __init__(self) -> None: ...

class PostfixNotationTokenType(enum.Enum):
    __new__: ClassVar[Callable] = ...
    BuildingBlock: ClassVar[PostfixNotationTokenType] = ...
    Reaction: ClassVar[PostfixNotationTokenType] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _hashable_values_: ClassVar[list] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[object]] = ...
    _unhashable_values_: ClassVar[list] = ...
    _unhashable_values_map_: ClassVar[dict] = ...
    _use_args_: ClassVar[bool] = ...
    _value2member_map_: ClassVar[dict] = ...
    _value_repr_: ClassVar[None] = ...
    __pybind11_native_enum__: ClassVar[PyCapsule] = ...

class ReactantLists:
    def __init__(self) -> None: ...
    def get(self, reaction_index: typing.SupportsInt | typing.SupportsIndex, reactant_index: typing.SupportsInt | typing.SupportsIndex) -> list[int]: ...
    def num_matches(self) -> int: ...

class ReactantMatchingConfig:
    selectivity_cutoff: int
    def __init__(self) -> None: ...
    def check(self, match: ReactionMatch) -> bool: ...

class ReactionCSVConfig:
    name_column: str
    reactant_name_column: str
    reactant_name_delimiter: str
    smarts_column: str
    def __init__(self) -> None: ...

class ReactionEntry:
    name: str
    reaction: prexsyn_engine.chemistry.Reaction
    def __init__(self) -> None: ...

class ReactionItem(ReactionEntry):
    def __init__(self) -> None: ...
    @property
    def index(self) -> int: ...

class ReactionLibrary:
    def __init__(self) -> None: ...
    def add(self, entry: ReactionEntry) -> int: ...
    @staticmethod
    def deserialize(path: os.PathLike | str | bytes) -> ReactionLibrary: ...
    @overload
    def get(self, index: typing.SupportsInt | typing.SupportsIndex) -> ReactionItem: ...
    @overload
    def get(self, name: str) -> ReactionItem: ...
    def match_reactants(self, molecule: prexsyn_engine.chemistry.Molecule) -> list[ReactionMatch]: ...
    def serialize(self, path: os.PathLike | str | bytes) -> None: ...
    def size(self) -> int: ...
    def __getitem__(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> ReactionItem: ...
    def __len__(self) -> int: ...

class ReactionMatch:
    def __init__(self, *args, **kwargs) -> None: ...
    @property
    def count(self) -> int: ...
    @property
    def reactant_index(self) -> int: ...
    @property
    def reactant_name(self) -> str: ...
    @property
    def reaction_index(self) -> int: ...
    @property
    def reaction_name(self) -> str: ...

class Synthesis:
    def __init__(self, *args, **kwargs) -> None: ...
    @overload
    def add_building_block(self, index: typing.SupportsInt | typing.SupportsIndex) -> SynthesisResult: ...
    @overload
    def add_building_block(self, identifier: str) -> SynthesisResult: ...
    @overload
    def add_intermediate(self, index: typing.SupportsInt | typing.SupportsIndex, max_outcomes: typing.SupportsInt | typing.SupportsIndex | None) -> SynthesisResult: ...
    @overload
    def add_intermediate(self, identifier: str, max_outcomes: typing.SupportsInt | typing.SupportsIndex | None) -> SynthesisResult: ...
    def add_postfix_notation(self, postfix_notation: PostfixNotation, max_outcomes: typing.SupportsInt | typing.SupportsIndex | None) -> SynthesisResult: ...
    @overload
    def add_reaction(self, index: typing.SupportsInt | typing.SupportsIndex, max_outcomes: typing.SupportsInt | typing.SupportsIndex | None) -> SynthesisResult: ...
    @overload
    def add_reaction(self, name: str, max_outcomes: typing.SupportsInt | typing.SupportsIndex | None) -> SynthesisResult: ...
    def chemical_space(self) -> ChemicalSpace: ...
    def count_building_blocks(self) -> int: ...
    def count_reactions(self) -> int: ...
    @staticmethod
    def deserialize(data: bytes, chemspace: ChemicalSpace, max_outcomes: typing.SupportsInt | typing.SupportsIndex | None) -> Synthesis: ...
    def postfix_notation(self) -> PostfixNotation: ...
    def products(self) -> list[prexsyn_engine.chemistry.Molecule]: ...
    def serialize(self) -> bytes: ...
    def synthesis(self) -> prexsyn_engine.chemistry.Synthesis: ...
    def undo(self) -> SynthesisResult: ...

class SynthesisResult:
    def __init__(self) -> None: ...
    @staticmethod
    def error(message: str) -> SynthesisResult: ...
    @staticmethod
    def ok() -> SynthesisResult: ...
    def __bool__(self) -> bool: ...
    @property
    def is_ok(self) -> bool: ...
    @property
    def message(self) -> str: ...

def bb_lib_from_csv(path: os.PathLike | str | bytes, config: BuildingBlockCSVConfig = ..., preprocessor: BuildingBlockPreprocessor = ...) -> BuildingBlockLibrary: ...
def bb_lib_from_sdf(path: os.PathLike | str | bytes, preprocessor: BuildingBlockPreprocessor = ...) -> BuildingBlockLibrary: ...
def rxn_lib_from_csv(path: os.PathLike | str | bytes, config: ReactionCSVConfig = ..., ignore_errors: bool = ...) -> ReactionLibrary: ...
def rxn_lib_from_json(path: os.PathLike | str | bytes, ignore_errors: bool = ...) -> ReactionLibrary: ...
def rxn_lib_from_plain_text(path: os.PathLike | str | bytes, ignore_errors: bool = ...) -> ReactionLibrary: ...
