import collections.abc
import numpy
import prexsyn_engine.chemistry
import prexsyn_engine.chemspace
import typing
from typing import overload

class MorganFingerprint(_MoleculeDescriptor):
    def __init__(self, *args, **kwargs) -> None: ...
    @staticmethod
    def ecfp4() -> MorganFingerprint: ...
    @staticmethod
    def fcfp4() -> MorganFingerprint: ...

class SynthesisPostfixNotation(_SynthesisDescriptor):
    def __init__(self, *args, **kwargs) -> None: ...
    @overload
    @staticmethod
    def create(token_def: TokenDef, max_length: typing.SupportsInt | typing.SupportsIndex = ...) -> SynthesisPostfixNotation: ...
    @overload
    @staticmethod
    def create(max_length: typing.SupportsInt | typing.SupportsIndex = ...) -> SynthesisPostfixNotation: ...

class TokenDef:
    bb: int
    end: int
    pad: int
    rxn: int
    start: int
    def __init__(self) -> None: ...
    @staticmethod
    def from_dict(arg0: dict) -> TokenDef: ...

class _MoleculeDescriptor:
    def __init__(self, *args, **kwargs) -> None: ...
    def dtype(self) -> numpy.dtype: ...
    def num_elements(self) -> int: ...
    def size(self) -> list[int]: ...
    def size_in_bytes(self) -> int: ...
    @overload
    def __call__(self, arg0: prexsyn_engine.chemistry.Molecule) -> numpy.ndarray: ...
    @overload
    def __call__(self, arg0: collections.abc.Sequence[prexsyn_engine.chemistry.Molecule]) -> numpy.ndarray: ...

class _SynthesisDescriptor:
    def __init__(self, *args, **kwargs) -> None: ...
    def dtype(self) -> numpy.dtype: ...
    def num_elements(self) -> int: ...
    def size(self) -> list[int]: ...
    def size_in_bytes(self) -> int: ...
    @overload
    def __call__(self, arg0: prexsyn_engine.chemspace.Synthesis) -> numpy.ndarray: ...
    @overload
    def __call__(self, arg0: collections.abc.Sequence[prexsyn_engine.chemspace.Synthesis]) -> numpy.ndarray: ...
