context:
  rdkit_min_version: "2025.3.6"

package:
  name: prexsyn-engine
  version: 0.1.0

build:
  script: |
    mkdir builddir
    $PYTHON -m build -w -n -x -Cbuilddir=builddir
    $PYTHON -m pip install dist/*.whl

source:
  path: ../
  use_gitignore: true

requirements:
  build:
  - ${{ compiler('cxx') }}
  - llvm-openmp
  - cmake
  - ninja

  host:
  - python
  - pip
  - setuptools
  - python-build
  - rdkit >=${{ rdkit_min_version }}
  - librdkit-dev >=${{ rdkit_min_version }}
  - libboost-devel
  - libboost-python-devel
  - llvm-openmp
  - eigen
  - spdlog >=1.15.3,<2

  run:
  - python
  - numpy >=2.0.0,<3
  - rdkit >=${{ rdkit_min_version }}
  - libboost
  - libboost-python
  - llvm-openmp

  ignore_run_exports:
    from_package:
    - spdlog

tests:
- python:
    imports:
    - prexsyn_engine
