from .types import Reaction

class ReactionList:
    def __getitem__(self, index: int) -> Reaction: ...
    def __len__(self) -> int: ...
    def save(self, path: str) -> None: ...
    @staticmethod
    def load(path: str) -> "ReactionList": ...
    @staticmethod
    def from_txt(path: str) -> "ReactionList": ...
