name: Build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [published]
jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Cache third-party deps
        uses: actions/cache@v5
        with:
          path: .cache/third_party
          key: ${{ runner.os }}-third-party-${{ hashFiles('CMakeLists.txt', 'third_party/boost.sh', 'third_party/rdkit.sh') }}
      - name: Build wheels
        uses: pypa/cibuildwheel@v3.4.0
        env:
          CIBW_BEFORE_ALL_LINUX: >-
            mkdir -p /host${{ github.workspace }}/.cache/third_party && mkdir -p /project/build/scikit-build && rm -rf /project/build/scikit-build/_third_party && ln -s /host${{ github.workspace }}/.cache/third_party /project/build/scikit-build/_third_party
      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
  make_sdist:
    name: Make SDist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Build SDist
        run: pipx run build --sdist
      - uses: actions/upload-artifact@v4
        with:
          name: cibw-sdist
          path: dist/*.tar.gz
  publish_pypi:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    needs: [build_wheels, make_sdist]
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - uses: actions/download-artifact@v5
        with:
          path: dist
          pattern: cibw-*
          merge-multiple: true
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
